//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GatoWebServiceCliente.TITANIC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:webapps_gato", ConfigurationName="TITANIC.webapps_gatoPort")]
    public interface webapps_gatoPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:webapps_gato#Gato#newGame", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void newGame();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:webapps_gato#Gato#newGame", ReplyAction="*")]
        System.Threading.Tasks.Task newGameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:webapps_gato#Gato#play", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string play(int simbolo, int indice);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:webapps_gato#Gato#play", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> playAsync(int simbolo, int indice);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:webapps_gato#Gato#checkWinner", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool checkWinner();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:webapps_gato#Gato#checkWinner", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> checkWinnerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:webapps_gato#Gato#getWinner", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getWinner();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:webapps_gato#Gato#getWinner", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getWinnerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:webapps_gato#Gato#getBoard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getBoard();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:webapps_gato#Gato#getBoard", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getBoardAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:webapps_gato#Gato#saveScores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void saveScores(string ranking);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:webapps_gato#Gato#saveScores", ReplyAction="*")]
        System.Threading.Tasks.Task saveScoresAsync(string ranking);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:webapps_gato#Gato#loadScores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string loadScores();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:webapps_gato#Gato#loadScores", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> loadScoresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface webapps_gatoPortChannel : GatoWebServiceCliente.TITANIC.webapps_gatoPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class webapps_gatoPortClient : System.ServiceModel.ClientBase<GatoWebServiceCliente.TITANIC.webapps_gatoPort>, GatoWebServiceCliente.TITANIC.webapps_gatoPort {
        
        public webapps_gatoPortClient() {
        }
        
        public webapps_gatoPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public webapps_gatoPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webapps_gatoPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webapps_gatoPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void newGame() {
            base.Channel.newGame();
        }
        
        public System.Threading.Tasks.Task newGameAsync() {
            return base.Channel.newGameAsync();
        }
        
        public string play(int simbolo, int indice) {
            return base.Channel.play(simbolo, indice);
        }
        
        public System.Threading.Tasks.Task<string> playAsync(int simbolo, int indice) {
            return base.Channel.playAsync(simbolo, indice);
        }
        
        public bool checkWinner() {
            return base.Channel.checkWinner();
        }
        
        public System.Threading.Tasks.Task<bool> checkWinnerAsync() {
            return base.Channel.checkWinnerAsync();
        }
        
        public string getWinner() {
            return base.Channel.getWinner();
        }
        
        public System.Threading.Tasks.Task<string> getWinnerAsync() {
            return base.Channel.getWinnerAsync();
        }
        
        public string getBoard() {
            return base.Channel.getBoard();
        }
        
        public System.Threading.Tasks.Task<string> getBoardAsync() {
            return base.Channel.getBoardAsync();
        }
        
        public void saveScores(string ranking) {
            base.Channel.saveScores(ranking);
        }
        
        public System.Threading.Tasks.Task saveScoresAsync(string ranking) {
            return base.Channel.saveScoresAsync(ranking);
        }
        
        public string loadScores() {
            return base.Channel.loadScores();
        }
        
        public System.Threading.Tasks.Task<string> loadScoresAsync() {
            return base.Channel.loadScoresAsync();
        }
    }
}
